# Site settings
title: Ariel Ashtamker
description: Las Vegas, NV
baseurl: "/lens-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
email_url: ashtamker@hotmail.com
instagram_url: https://www.instagram.com/casperthechiweenie

# Build settings
markdown: kramdown
